In [3]:
print('What is your name?')
name = input()
print('Hello',name)

What is your name?
Mhiko
Hello Mhiko


In [9]:
subjects = ['a','b','c','d']
print(subjects[3])
subjects[0] = 'Science'
print(subjects[1:])

d
['b', 'c', 'd']


In [0]:
scientist = {'Name:','Alan Turing'}

In [14]:
import numpy as np

x = np.array(['1','2','3'])
np.zeros((2,2))
np.ones((2,2))
np.random.randint(10,size=(5))

a = np.random.randint(10,size=(5))
b = np.random.randint(10,size=(5))

print(a)
print(b)
print(a+b)

# np.random.random - float

#add arrays
x = np.array([1,2,3])
y = np.array([4,5,6])

# np.argmax - index of highest value

for number in x:
  print(number, end=' ')

[3 7 5 1 6]
[9 9 4 8 7]
[12 16  9  9 13]


TypeError: ignored